on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Lint project
        run: go vet ./...
      - name: Build project
        run: go build ./...
      - name: Test project
        run: go test ./...
